// This file is auto-generated by @hey-api/openapi-ts

export type Todo = {
    summary: string;
    completed: string;
};

export type GetApiTodosData = {
    body?: never;
    path?: never;
    query?: {
        page_size?: unknown;
        page_token?: unknown;
    };
    url: '/api/todos';
};

export type GetApiTodosResponses = {
    /**
     * List of Todos
     */
    200: Array<Todo>;
};

export type GetApiTodosResponse = GetApiTodosResponses[keyof GetApiTodosResponses];

export type PostApiTodosData = {
    /**
     * The Todo to create
     */
    body: Todo;
    path?: never;
    query?: never;
    url: '/api/todos';
};

export type PostApiTodosResponses = {
    /**
     * The created Todo
     */
    200: Todo;
};

export type PostApiTodosResponse = PostApiTodosResponses[keyof PostApiTodosResponses];

export type DeleteApiTodosByTodoData = {
    body?: never;
    path: {
        todo: unknown;
    };
    query?: never;
    url: '/api/todos/{todo}';
};

export type DeleteApiTodosByTodoResponses = {
    /**
     * The deleted Todo
     */
    200: unknown;
};

export type GetApiTodosByTodoData = {
    body?: never;
    path: {
        todo: string;
    };
    query?: never;
    url: '/api/todos/{todo}';
};

export type GetApiTodosByTodoResponses = {
    /**
     * Got Todo
     */
    200: Todo;
};

export type GetApiTodosByTodoResponse = GetApiTodosByTodoResponses[keyof GetApiTodosByTodoResponses];

export type PostApiTodosByTodoData = {
    /**
     * The Todo to update
     */
    body: Todo;
    path: {
        todo: unknown;
    };
    query?: never;
    url: '/api/todos/{todo}';
};

export type PostApiTodosByTodoResponses = {
    /**
     * The updated Todo
     */
    200: Todo;
};

export type PostApiTodosByTodoResponse = PostApiTodosByTodoResponses[keyof PostApiTodosByTodoResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};