// This file is auto-generated by @hey-api/openapi-ts

export type GetApiTodosData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/todos';
};

export type GetApiTodosResponses = {
    /**
     * OK
     */
    200: Array<{
        summary: string;
        completed: string;
    }>;
};

export type GetApiTodosResponse = GetApiTodosResponses[keyof GetApiTodosResponses];

export type PostApiTodosData = {
    body?: {
        summary: string;
        completed: string;
    };
    path?: never;
    query?: never;
    url: '/api/todos';
};

export type PostApiTodosResponses = {
    /**
     * Created
     */
    200: unknown;
};

export type DeleteApiTodosByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/todos/{id}';
};

export type DeleteApiTodosByIdResponses = {
    /**
     * Deleted
     */
    200: unknown;
};

export type GetApiTodosByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/todos/{id}';
};

export type GetApiTodosByIdResponses = {
    /**
     * OK
     */
    200: {
        summary: string;
        completed: string;
    };
};

export type GetApiTodosByIdResponse = GetApiTodosByIdResponses[keyof GetApiTodosByIdResponses];

export type PostApiTodosByIdData = {
    body?: {
        summary: string;
        completed: string;
    };
    path: {
        id: string;
    };
    query?: never;
    url: '/api/todos/{id}';
};

export type PostApiTodosByIdResponses = {
    /**
     * Updated
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};